[project]
name = "baka-warp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "pillow>=12.1.0",
    "pytest>=9.0.2",
    "warp-lang>=1.11.0",
]
